// Default theme configuration — matches the existing Shopify.jsx design
const DEFAULT_THEME = {
  colors: {
    primary: "#e8540a",
    primaryHover: "#c94708",
    secondary: "#1a1208",
    accent: "#f9c97a",
    cta: "#e8540a",
    ctaHover: "#c94708",
    background: "#FDFAF6",
    surface: "#FFFFFF",
    cardBackground: "#FFFFFF",
    darkSection: "#1a1208",
    lightSection: "#f8f4ed",
    headingColor: "#1a1208",
    bodyText: "#3d3020",
    mutedText: "#9e9789",
    linkColor: "#e8540a",
    linkHover: "#c94708",
    borderColor: "#ece6dd",
    dividerColor: "#f0ebe3",
    ratingStarColor: "#f9c97a",
    ratingStarEmpty: "#e0d9ce",
    successColor: "#3d7a4e",
    warningColor: "#f59e0b",
    errorColor: "#ef4444",
    badgeBackground: "#e8540a",
    badgeText: "#FFFFFF",
    inputBackground: "#FFFFFF",
    inputBorder: "#ece6dd",
    buttonText: "#FFFFFF",
    buttonBackground: "#e8540a",
    footerBackground: "#1a1208",
    footerHeading: "#f9c97a",
    footerText: "#9e8e7a",
    footerLink: "#9e8e7a",
    footerLinkHover: "#FFFFFF",
  },
  sectionColors: {
    announcementBar: { bg: "#1a1208", text: "#f9c97a" },
    header: { bg: "#FFFFFF", text: "#3d3020" },
    navigation: { bg: "#FFFFFF", text: "#3d3020", hover: "#e8540a" },
    breadcrumb: { bg: "#FFFFFF", text: "#9e9789", active: "#1a1208" },
    hero: { bg: "#1a1208", text: "#FFFFFF", subtitle: "#c8bfaf" },
    courseCard: { bg: "#FFFFFF", border: "#ece6dd" },
    curriculum: { bg: "#f8f4ed", headerBg: "#f8f4ed", text: "#1a1208" },
    requirements: { bg: "#f8f4ed", text: "#3d3020" },
    instructor: { bg: "#FFFFFF", text: "#1a1208" },
    reviews: { bg: "#FFFFFF", text: "#1a1208" },
    testimonials: { bg: "#FFFFFF", text: "#1a1208" },
    videoReviews: { bg: "#FFFFFF", text: "#1a1208" },
    relatedCourses: { bg: "#FFFFFF", text: "#1a1208" },
    footer: { bg: "#1a1208", text: "#9e8e7a" },
    stickyCta: { bg: "#FFFFFF", buttonBg: "linear-gradient(135deg, #FF5A00 0%, #FF6A00 100%)", buttonText: "#FFFFFF" },
  },
  typography: {
    primaryFont: "'DM Sans', sans-serif",
    headingFont: "'Playfair Display', serif",
    bodyFont: "'DM Sans', sans-serif",
    buttonFont: "'Inter', 'SF Pro Display', sans-serif",
    navigationFont: "'DM Sans', sans-serif",
    labelFont: "'DM Sans', sans-serif",
    priceFont: "'Playfair Display', serif",
    quoteFont: "'DM Sans', sans-serif",
    headings: {
      h1: { fontSize: { desktop: "3.5rem", tablet: "2.5rem", mobile: "1.875rem" }, fontWeight: "700", lineHeight: "1.15", letterSpacing: "-0.02em", textTransform: "none", color: "", alignment: "left" },
      h2: { fontSize: { desktop: "2.5rem", tablet: "1.875rem", mobile: "1.5rem" }, fontWeight: "700", lineHeight: "1.2", letterSpacing: "-0.01em", textTransform: "none", color: "", alignment: "left" },
      h3: { fontSize: { desktop: "1.5rem", tablet: "1.25rem", mobile: "1.125rem" }, fontWeight: "700", lineHeight: "1.3", letterSpacing: "0", textTransform: "none", color: "", alignment: "left" },
      h4: { fontSize: { desktop: "1.25rem", tablet: "1.125rem", mobile: "1rem" }, fontWeight: "600", lineHeight: "1.4", letterSpacing: "0", textTransform: "none", color: "", alignment: "left" },
      h5: { fontSize: { desktop: "1.125rem", tablet: "1rem", mobile: "0.875rem" }, fontWeight: "600", lineHeight: "1.5", letterSpacing: "0", textTransform: "none", color: "", alignment: "left" },
      h6: { fontSize: { desktop: "1rem", tablet: "0.875rem", mobile: "0.8125rem" }, fontWeight: "600", lineHeight: "1.5", letterSpacing: "0", textTransform: "none", color: "", alignment: "left" },
    },
    body: { fontSize: "1rem", fontWeight: "400", lineHeight: "1.7", letterSpacing: "0", color: "" },
    buttons: { fontSize: "1rem", fontWeight: "700", letterSpacing: "0", textTransform: "none" },
  },
  layout: {
    pageMaxWidth: "80rem",
    containerWidth: "100%",
    sectionPadding: { top: { desktop: "4rem", tablet: "3rem", mobile: "2rem" }, bottom: { desktop: "4rem", tablet: "3rem", mobile: "2rem" }, left: "1rem", right: "1rem" },
    elementGap: "1.5rem",
    gridGap: "1.5rem",
    cardGap: "1.5rem",
    borderRadius: "1rem",
    buttonRadius: "0.75rem",
    imageRadius: "1rem",
    shadow: "0 1px 3px rgba(0,0,0,0.08)",
    borderWidth: "1px",
    globalCardRadius: "1rem",
    globalButtonRadius: "0.75rem",
    globalShadow: "0 1px 3px rgba(0,0,0,0.08)",
  },
  announcementBar: {
    enabled: true,
    text: "🎉 Limited Time Offer: Save {discount}% — Ends Soon!",
    backgroundColor: "#1a1208",
    textColor: "#f9c97a",
    fontFamily: "",
    fontSize: { desktop: "1rem", mobile: "0.875rem" },
    fontWeight: "600",
    height: "auto",
    alignment: "center",
    padding: "0.5rem 1rem",
    letterSpacing: "0",
    link: "",
    linkTarget: "_self",
    showCountdown: false,
    countdownDate: "",
    closeButton: false,
    speed: 18,
  },
  header: {
    logoText: "Lerni",
    logoAccent: "ni",
    logoAccentColor: "#e8540a",
    logoImage: "",
    logoWidth: "auto",
    logoHeight: "auto",
    logoPosition: "center",
    backgroundColor: "#FFFFFF",
    height: "auto",
    padding: "0.75rem 1rem",
    navigationFont: "",
    navigationColor: "#3d3020",
    navigationHoverColor: "#e8540a",
    loginButtonText: "Log In",
    loginButtonBg: "#e8540a",
    loginButtonColor: "#FFFFFF",
    loginButtonHoverBg: "#c94708",
    loginButtonRadius: "0.5rem",
    mobileMenuBg: "#1a1208",
  },
  breadcrumbs: {
    enabled: true,
    backgroundColor: "#FFFFFF",
    textColor: "#9e9789",
    activeTextColor: "#1a1208",
    fontFamily: "",
    fontSize: "0.875rem",
    spacing: "0.5rem",
    separator: "›",
    separatorColor: "#ccc5b8",
    padding: "0.5rem 0",
  },
  hero: {
    backgroundColor: "#1a1208",
    backgroundImage: "",
    gradient: "",
    overlayColor: "",
    overlayOpacity: 0,
    badge: { enabled: true, backgroundColor: "#e8540a", textColor: "#FFFFFF", fontFamily: "", fontSize: "0.875rem", padding: "0.375rem 0.75rem", radius: "0.25rem" },
    title: { fontFamily: "", fontSize: { desktop: "3.5rem", tablet: "2.5rem", mobile: "1.875rem" }, fontWeight: "700", lineHeight: "1.15", letterSpacing: "0", color: "#FFFFFF", maxWidth: "", alignment: "left" },
    subtitle: { color: "#c8bfaf", fontSize: { desktop: "1.5rem", tablet: "1.25rem", mobile: "1.125rem" } },
    image: { borderRadius: "0", overlay: "", overlayOpacity: 0.3, playButtonSize: "4rem", playButtonColor: "#e8540a", playButtonHoverColor: "#c94708", freeLectureBadge: true, freeLectureText: "Free Lectures", freeLectureBg: "rgba(255,255,255,0.9)", freeLectureColor: "#1a1208" },
    meta: { ratingVisible: true, studentsVisible: true, instructorVisible: true, updatedDateVisible: true, languageVisible: true, iconColor: "", textColor: "#c8bfaf", fontFamily: "", spacing: "1rem" },
  },
  stickyCta: {
    enableDesktop: false,
    enableMobile: true,
    position: "bottom",
    backgroundColor: "#FFFFFF",
    buttonBackground: "linear-gradient(135deg, #FF5A00 0%, #FF6A00 100%)",
    buttonHoverBackground: "",
    buttonTextColor: "#FFFFFF",
    discountTextColor: "#000000",
    fontFamily: "'Inter', 'SF Pro Display', sans-serif",
    fontSize: { desktop: "1rem", mobile: "0.875rem" },
    fontWeight: "800",
    borderRadius: "0.75rem",
    shadow: "0 8px 24px rgba(255, 90, 0, 0.25)",
    height: "auto",
    padding: "0.75rem",
    safeArea: true,
  },
  whatYoullLearn: {
    enabled: true,
    heading: "What you'll learn",
    headingFont: "",
    headingSize: "",
    headingColor: "",
    backgroundColor: "#f8f4ed",
    cardBackground: "",
    border: "1px solid #ece6dd",
    borderRadius: "1rem",
    shadow: "",
    padding: { desktop: "2rem", mobile: "1rem" },
    itemSpacing: "1rem",
    icon: "check",
    iconColor: "#FFFFFF",
    iconBackground: "#e8540a",
    textColor: "#3d3020",
    textFont: "",
    textSize: { desktop: "1rem", mobile: "0.875rem" },
  },
  curriculum: {
    enabled: true,
    heading: "Course Content",
    headingFont: "",
    headingSize: "",
    headingColor: "",
    backgroundColor: "#FFFFFF",
    cardBackground: "#FFFFFF",
    border: "1px solid #ece6dd",
    borderRadius: "0.75rem",
    sectionSpacing: "0.5rem",
    lectureRowHeight: "auto",
    lectureFont: "",
    lectureFontSize: "",
    lectureColor: "#1a1208",
    freeLectureBadge: true,
    freeLectureBadgeColor: "#9a3c0e",
    freeLectureBadgeBg: "#fde8d8",
    expandIconColor: "#9e9789",
    sectionHeaderBg: "#f8f4ed",
    sectionHeaderHoverBg: "#f0ebe3",
    style: "accordion",
  },
  requirements: {
    enabled: true,
    heading: "Requirements",
    headingFont: "",
    headingSize: "",
    headingColor: "",
    backgroundColor: "#f8f4ed",
    cardBackground: "",
    border: "1px solid #ece6dd",
    borderRadius: "1rem",
    icon: "check",
    iconBackground: "#e8540a",
    iconColor: "#FFFFFF",
    textColor: "#3d3020",
    textFont: "",
    spacing: "1rem",
    padding: { desktop: "2rem", mobile: "1rem" },
  },
  description: {
    enabled: true,
    heading: "Description",
    headingFont: "",
    headingSize: "",
    headingColor: "",
    bodyFont: "",
    bodySize: { desktop: "1rem", mobile: "0.875rem" },
    lineHeight: "1.8",
    textColor: "#3d3020",
    maxWidth: "",
    backgroundColor: "",
    readMoreText: "Show more",
    readLessText: "Show less",
    readMoreColor: "#e8540a",
    collapsedHeight: "12rem",
  },
  instructorSection: {
    enabled: true,
    heading: "Instructor",
    headingFont: "",
    headingSize: "",
    headingColor: "",
    imageSize: "100%",
    imageShape: "square",
    imageRadius: "0",
    imageObjectFit: "contain",
    nameFont: "",
    nameSize: { desktop: "1.5rem", mobile: "1.25rem" },
    usernameFont: "",
    usernameSize: "1rem",
    statCardBg: "#FFFFFF",
    statCardBorder: "1px solid #ece6dd",
    statCardRadius: "0.75rem",
    statCardShadow: "0 1px 2px rgba(0,0,0,0.05)",
    iconColor: "",
    numberFont: "",
    numberSize: { desktop: "1.5rem", mobile: "1.25rem" },
    labelFont: "",
    labelSize: { desktop: "0.875rem", mobile: "0.75rem" },
  },
  ratings: {
    enabled: true,
    starStyle: "filled",
    starColor: "#f9c97a",
    emptyStarColor: "#e0d9ce",
    starSize: { desktop: "3rem", mobile: "2.25rem" },
    ratingFont: "",
    ratingSize: { desktop: "2.5rem", mobile: "2rem" },
    countFont: "",
    countSize: "1rem",
    spacing: "1rem",
    alignment: "left",
  },
  reviews: {
    enabled: true,
    heading: "",
    subtitle: "",
    cardWidth: { desktop: "380px", mobile: "min(88vw,340px)" },
    cardHeight: "auto",
    cardBackground: "#FFFFFF",
    border: "1px solid #ece6dd",
    borderRadius: "1rem",
    shadow: "0 1px 2px rgba(0,0,0,0.05)",
    reviewerImageSize: { desktop: "3.5rem", mobile: "3rem" },
    reviewerNameFont: "",
    reviewTextFont: "",
    ratingStars: true,
    starColor: "#f9c97a",
    dateColor: "#9e9789",
    arrowStyle: "circle",
    arrowColor: "#1a1208",
    visibleCount: { desktop: 3, mobile: 1 },
    autoplay: false,
    autoplaySpeed: 5000,
  },
  testimonials: {
    enabled: true,
    heading: "Student Testimonials",
    subtitle: "See what our students have to say",
    headingFont: "",
    headingSize: "",
    cardLayout: "carousel",
    cardWidth: "200px",
    cardHeight: "390px",
    imageRadius: "0.75rem",
    borderRadius: "0.75rem",
    spacing: "0.75rem",
    backgroundColor: "",
    speed: 4,
  },
  videoReviews: {
    enabled: true,
    heading: "Video Reviews",
    subtitle: "Watch authentic testimonials from our graduates",
    headingFont: "",
    headingSize: "",
    subtitleFont: "",
    cardWidth: "200px",
    cardHeight: "390px",
    videoAspectRatio: "",
    videoRadius: "0.75rem",
    videoShadow: "0 4px 6px rgba(0,0,0,0.1)",
    gap: "0.75rem",
    playButtonColor: "#FFFFFF",
    playButtonSize: "3rem",
    autoplay: false,
  },
  relatedCourses: {
    enabled: true,
    heading: "Students also bought",
    headingFont: "",
    headingSize: "",
    cardLayout: "grid",
    numberOfCards: 4,
    cardWidth: "",
    imageAspectRatio: "16/9",
    imageRadius: "0",
    cardBackground: "#FFFFFF",
    border: "1px solid #ece6dd",
    shadow: "0 1px 3px rgba(0,0,0,0.08)",
    courseTitleFont: "",
    instructorFont: "",
    spacing: "1.5rem",
  },
  footer: {
    enabled: true,
    backgroundColor: "#1a1208",
    textColor: "#9e8e7a",
    headingColor: "#f9c97a",
    linkColor: "#9e8e7a",
    linkHoverColor: "#FFFFFF",
    padding: { desktop: "3rem 0", mobile: "2rem 0" },
    fontFamily: "",
    logoText: "Lerni",
    logoAccent: "ni",
    logoAccentColor: "#f9c97a",
    copyrightText: "© 2024 Lerni, Inc. All rights reserved.",
    columns: [
      { heading: "Lerni", links: [{ text: "About", url: "/" }, { text: "Press", url: "/" }, { text: "Contact", url: "/" }, { text: "Careers", url: "/" }] },
      { heading: "Community", links: [{ text: "Learners", url: "/" }, { text: "Partners", url: "/" }, { text: "Developers", url: "/" }, { text: "Beta Testers", url: "/" }] },
      { heading: "Teaching", links: [{ text: "Become Instructor", url: "/" }, { text: "Teaching Center", url: "/" }, { text: "Resources", url: "/" }] },
      { heading: "Programs", links: [{ text: "Enterprise", url: "/" }, { text: "Government", url: "/" }, { text: "Lerni Business", url: "/" }] },
      { heading: "Support", links: [{ text: "Help Center", url: "/" }, { text: "Get the App", url: "/" }, { text: "FAQ", url: "/" }, { text: "Accessibility", url: "/" }] },
      { heading: "Legal", links: [{ text: "Terms", url: "/" }, { text: "Privacy Policy", url: "/" }, { text: "Cookie Settings", url: "/" }, { text: "Sitemap", url: "/" }] },
    ],
  },
  buttons: {
    primary: { background: "#e8540a", textColor: "#FFFFFF", hoverBackground: "#c94708", hoverText: "#FFFFFF", border: "none", borderColor: "", hoverBorder: "", radius: "0.75rem", height: "auto", padding: "0.75rem 1.5rem", fontFamily: "", fontSize: "1rem", fontWeight: "700", letterSpacing: "0", shadow: "0 4px 12px rgba(232,84,10,0.2)" },
    secondary: { background: "#FFFFFF", textColor: "#1a1208", hoverBackground: "#f8f4ed", hoverText: "#1a1208", border: "2px solid #ece6dd", borderColor: "#ece6dd", hoverBorder: "", radius: "0.75rem", height: "auto", padding: "0.75rem 1.5rem", fontFamily: "", fontSize: "1rem", fontWeight: "600", letterSpacing: "0", shadow: "" },
    outline: { background: "transparent", textColor: "#e8540a", hoverBackground: "#fdf2ea", hoverText: "#e8540a", border: "2px solid #e8540a", borderColor: "#e8540a", hoverBorder: "", radius: "0.75rem", height: "auto", padding: "0.75rem 1.5rem", fontFamily: "", fontSize: "1rem", fontWeight: "700", letterSpacing: "0", shadow: "" },
    ghost: { background: "transparent", textColor: "#3d3020", hoverBackground: "#f8f4ed", hoverText: "#1a1208", border: "none", borderColor: "", hoverBorder: "", radius: "0.75rem", height: "auto", padding: "0.75rem 1.5rem", fontFamily: "", fontSize: "1rem", fontWeight: "500", letterSpacing: "0", shadow: "" },
  },
  sectionOrder: [
    "hero",
    "whatYoullLearn",
    "curriculum",
    "requirements",
    "description",
    "instructor",
    "reviews",
    "testimonials",
    "videoReviews",
    "relatedCourses",
  ],
  sectionVisibility: {
    announcementBar: true,
    header: true,
    breadcrumbs: true,
    hero: true,
    whatYoullLearn: true,
    curriculum: true,
    requirements: true,
    description: true,
    instructor: true,
    reviews: true,
    testimonials: true,
    videoReviews: true,
    relatedCourses: true,
    footer: true,
    stickyCta: true,
  },
};

export default DEFAULT_THEME;
